const API = (window.STEPSTYLE_API_BASE_URL || 'https://backend-production-8aa5.up.railway.app').replace(/\/$/, '');
const tokenKey = 'stepstyle_admin_token';
let appointments = [], messages = [];
const $ = (id) => document.getElementById(id);

function toast(message, error=false){const el=$('toast');el.textContent=message;el.classList.toggle('error-toast',error);el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function authHeaders(){return {Authorization:`Bearer ${localStorage.getItem(tokenKey)}`,'Content-Type':'application/json'}}
async function api(path, options={}){const res=await fetch(API+path,{...options,headers:{...authHeaders(),...(options.headers||{})}});let data={};try{data=await res.json()}catch{}if(res.status===401){logout(false);throw new Error('Your session has expired.')}if(!res.ok)throw new Error(data.message||'Request failed');return data}

function showDashboard(){ $('loginView').classList.add('hidden'); $('dashboardView').classList.remove('hidden'); loadAll(); }
function logout(show=true){const token=localStorage.getItem(tokenKey);localStorage.removeItem(tokenKey);if(token) fetch(API+'/api/admin/logout',{method:'POST',headers:{Authorization:`Bearer ${token}`}}).catch(()=>{});$('dashboardView').classList.add('hidden');$('loginView').classList.remove('hidden');if(show)toast('Logged out')}

$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';try{const res=await fetch(API+'/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value.trim(),password:$('password').value})});const data=await res.json();if(!res.ok)throw new Error(data.message||'Invalid login');localStorage.setItem(tokenKey,data.token);showDashboard()}catch(err){$('loginError').textContent=err.message}});
$('logoutBtn').addEventListener('click',()=>logout());$('refreshBtn').addEventListener('click',loadAll);

document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>switchSection(btn.dataset.section)));
document.querySelectorAll('[data-go]').forEach(btn=>btn.addEventListener('click',()=>switchSection(btn.dataset.go)));
function switchSection(section){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===section));document.querySelectorAll('.section').forEach(s=>s.classList.add('hidden'));$(`${section}Section`).classList.remove('hidden');$('pageTitle').textContent=section[0].toUpperCase()+section.slice(1);}

async function loadAll(){try{const [a,m]=await Promise.all([api('/api/appointments'),api('/api/messages')]);appointments=a.data||[];messages=m.data||[];renderAll()}catch(err){toast(err.message,true)}}
function renderAll(){const pending=appointments.filter(a=>a.status==='Pending').length, confirmed=appointments.filter(a=>a.status==='Confirmed').length;$('totalAppointments').textContent=appointments.length;$('pendingAppointments').textContent=pending;$('confirmedAppointments').textContent=confirmed;$('totalMessages').textContent=messages.length;renderRecent();renderAppointments();renderMessages()}
function formatDate(value){if(!value)return '-';const d=new Date(value);return Number.isNaN(d.getTime())?esc(value):d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}
function renderRecent(){const rows=appointments.slice(0,5).map(a=>`<tr><td><strong>${esc(a.name)}</strong><br><span class="muted">${esc(a.email)}</span></td><td>${esc(a.date)}<br>${esc(a.time)}</td><td>${esc(a.dressType)}</td><td><span class="status ${esc(a.status)}">${esc(a.status)}</span></td></tr>`).join('');$('recentAppointments').innerHTML=rows?`<table class="data-table"><thead><tr><th>Customer</th><th>Date / time</th><th>Dress</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table>`:`<div class="empty">No appointments yet.</div>`}
function renderAppointments(){const q=($('appointmentSearch').value||'').toLowerCase();const status=$('appointmentFilter').value;const list=appointments.filter(a=>{const text=[a.name,a.phone,a.email,a.dressType,a.date].join(' ').toLowerCase();return(!q||text.includes(q))&&(!status||a.status===status)});const rows=list.map(a=>`<tr><td><strong>${esc(a.name)}</strong><br>${esc(a.phone)}<br><span class="muted">${esc(a.email)}</span></td><td>${esc(a.date)}<br>${esc(a.time)}</td><td>${esc(a.dressType)}<br><span class="muted">${esc(a.message||'')}</span></td><td><span class="status ${esc(a.status)}">${esc(a.status)}</span></td><td><div class="actions"><select onchange="updateStatus('${esc(a._id)}',this.value)">${['Pending','Confirmed','Completed','Cancelled'].map(s=>`<option ${s===a.status?'selected':''}>${s}</option>`).join('')}</select><button class="small-danger" onclick="deleteAppointment('${esc(a._id)}')">Delete</button></div></td></tr>`).join('');$('appointmentsTable').innerHTML=rows?`<table class="data-table"><thead><tr><th>Customer</th><th>Date / time</th><th>Order</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows}</tbody></table>`:`<div class="empty">No matching appointments.</div>`}
function renderMessages(){const rows=messages.map(m=>`<tr><td><strong>${esc(m.name)}</strong><br><span class="muted">${esc(m.email)}</span></td><td><strong>${esc(m.subject)}</strong><div class="message-cell">${esc(m.message)}</div></td><td>${formatDate(m.createdAt)}</td><td><button class="small-danger" onclick="deleteMessage('${esc(m._id)}')">Delete</button></td></tr>`).join('');$('messagesTable').innerHTML=rows?`<table class="data-table"><thead><tr><th>Customer</th><th>Message</th><th>Date</th><th>Action</th></tr></thead><tbody>${rows}</tbody></table>`:`<div class="empty">No messages yet.</div>`}

window.updateStatus=async(id,status)=>{try{await api(`/api/appointments/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});toast('Appointment updated');await loadAll()}catch(e){toast(e.message,true)}};
window.deleteAppointment=async id=>{if(!confirm('Delete this appointment?'))return;try{await api(`/api/appointments/${id}`,{method:'DELETE'});toast('Appointment deleted');await loadAll()}catch(e){toast(e.message,true)}};
window.deleteMessage=async id=>{if(!confirm('Delete this message?'))return;try{await api(`/api/messages/${id}`,{method:'DELETE'});toast('Message deleted');await loadAll()}catch(e){toast(e.message,true)}};
$('deleteAllAppointments').addEventListener('click',async()=>{if(!appointments.length||!confirm('Delete ALL appointments? This cannot be undone.'))return;try{await api('/api/appointments',{method:'DELETE'});toast('All appointments deleted');await loadAll()}catch(e){toast(e.message,true)}});
$('deleteAllMessages').addEventListener('click',async()=>{if(!messages.length||!confirm('Delete ALL messages? This cannot be undone.'))return;try{await api('/api/messages',{method:'DELETE'});toast('All messages deleted');await loadAll()}catch(e){toast(e.message,true)}});
$('appointmentSearch').addEventListener('input',renderAppointments);$('appointmentFilter').addEventListener('change',renderAppointments);

if(localStorage.getItem(tokenKey))showDashboard();
